/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AdditionProblem {
  'hindi' : string,
  'answer' : bigint,
  'firstNumber' : bigint,
  'telugu' : string,
  'secondNumber' : bigint,
  'english' : string,
}
export interface AnimalCard {
  'nameHindi' : string,
  'nameTelugu' : string,
  'nameEnglish' : string,
  'audioUrl' : string,
  'imageUrl' : string,
}
export interface BodyPart {
  'nameHindi' : string,
  'nameTelugu' : string,
  'nameEnglish' : string,
  'audioUrl' : string,
  'imageUrl' : string,
}
export interface Flashcard {
  'id' : bigint,
  'front' : string,
  'back' : string,
  'image' : string,
}
export interface GameSession {
  'userId' : Principal,
  'score' : bigint,
  'language' : string,
  'totalQuestions' : bigint,
  'timestamp' : Time,
  'gameType' : GameType,
}
export interface GameStatistics {
  'bestScore' : bigint,
  'totalScore' : bigint,
  'totalSessions' : bigint,
  'averageScore' : bigint,
}
export type GameType = { 'quiz' : null } |
  { 'matchingGame' : null } |
  { 'puzzle' : null } |
  { 'timedChallenge' : null };
export interface KidsProfile {
  'age' : bigint,
  'pin' : string,
  'name' : string,
  'avatar' : string,
}
export interface LearningContentPackage {
  'animalCards' : Array<AnimalCard>,
  'stateInfos' : Array<StateInfo>,
  'additionProblems' : Array<AdditionProblem>,
  'bodyParts' : Array<BodyPart>,
  'numberCards' : Array<NumberCard>,
  'plantCards' : Array<PlantCard>,
}
export interface Lesson {
  'id' : bigint,
  'title' : string,
  'body' : string,
  'image' : string,
}
export interface MiniGameContent {
  'id' : bigint,
  'pairs' : Array<[string, string]>,
}
export interface NumberCard {
  'hindi' : string,
  'audioUrl' : string,
  'number' : bigint,
  'telugu' : string,
  'english' : string,
}
export interface ParentalControls {
  'gamesAllowed' : Array<bigint>,
  'contentRestrictions' : Array<string>,
}
export interface PlantCard {
  'nameHindi' : string,
  'nameTelugu' : string,
  'nameEnglish' : string,
  'audioUrl' : string,
  'imageUrl' : string,
}
export interface QuizQuestion {
  'id' : bigint,
  'question' : string,
  'correctIndex' : bigint,
  'options' : Array<string>,
}
export interface QuizResult {
  'total' : bigint,
  'subject' : string,
  'score' : bigint,
}
export interface SessionProgress {
  'earnedBadges' : Array<string>,
  'completedLessons' : Array<bigint>,
  'quizResults' : Array<QuizResult>,
}
export interface StateInfo {
  'nameHindi' : string,
  'stateId' : bigint,
  'capitalEnglish' : string,
  'nameTelugu' : string,
  'nameEnglish' : string,
  'emoji' : string,
  'capitalHindi' : string,
  'capitalTelugu' : string,
}
export type Time = bigint;
export interface UserProfile {
  'name' : string,
  'email' : string,
  'avatarUrl' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'awardBadge' : ActorMethod<[Principal, string], undefined>,
  'completeLesson' : ActorMethod<[bigint], undefined>,
  'createKidsProfile' : ActorMethod<[KidsProfile], undefined>,
  'getAllSessionsProgress' : ActorMethod<[], Array<[string, SessionProgress]>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getDisplayName' : ActorMethod<[], [] | [string]>,
  'getFlashcards' : ActorMethod<[], Array<Flashcard>>,
  'getGameTypeAverage' : ActorMethod<
    [GameType],
    [] | [{ 'totalSessions' : bigint, 'averageScore' : bigint }]
  >,
  'getKidsProfile' : ActorMethod<[], [] | [KidsProfile]>,
  'getLearningContentPackage' : ActorMethod<[], LearningContentPackage>,
  'getLessons' : ActorMethod<[], Array<Lesson>>,
  'getMiniGameContent' : ActorMethod<[], Array<MiniGameContent>>,
  'getParentalControls' : ActorMethod<[], [] | [ParentalControls]>,
  'getQuizQuestions' : ActorMethod<[], Array<QuizQuestion>>,
  'getSessionProgress' : ActorMethod<[Principal], SessionProgress>,
  'getUserGameSessions' : ActorMethod<[Principal], Array<GameSession>>,
  'getUserGameStatistics' : ActorMethod<
    [Principal, GameType],
    [] | [GameStatistics]
  >,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'recordGameSession' : ActorMethod<
    [GameType, string, bigint, bigint],
    undefined
  >,
  'recordQuizResult' : ActorMethod<[string, bigint, bigint], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setDisplayName' : ActorMethod<[string], undefined>,
  'setParentalControls' : ActorMethod<[ParentalControls], undefined>,
  'setupContent' : ActorMethod<[], undefined>,
  'setupLearningContent' : ActorMethod<[], undefined>,
  'updateKidsPin' : ActorMethod<[string], undefined>,
  'updateKidsProfile' : ActorMethod<[KidsProfile], undefined>,
  'verifyKidsPin' : ActorMethod<[string], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];