/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Flashcard {
  'id' : bigint,
  'front' : string,
  'back' : string,
  'image' : string,
}
export interface GameSession {
  'userId' : Principal,
  'score' : bigint,
  'language' : string,
  'totalQuestions' : bigint,
  'timestamp' : Time,
  'gameType' : GameType,
}
export interface GameStatistics {
  'bestScore' : bigint,
  'totalScore' : bigint,
  'totalSessions' : bigint,
  'averageScore' : bigint,
}
export type GameType = { 'quiz' : null } |
  { 'matchingGame' : null } |
  { 'puzzle' : null } |
  { 'timedChallenge' : null };
export interface Lesson {
  'id' : bigint,
  'title' : string,
  'body' : string,
  'image' : string,
}
export interface MiniGameContent {
  'id' : bigint,
  'pairs' : Array<[string, string]>,
}
export interface QuizQuestion {
  'id' : bigint,
  'question' : string,
  'correctIndex' : bigint,
  'options' : Array<string>,
}
export interface QuizResult {
  'total' : bigint,
  'subject' : string,
  'score' : bigint,
}
export interface SessionProgress {
  'earnedBadges' : Array<string>,
  'completedLessons' : Array<bigint>,
  'quizResults' : Array<QuizResult>,
}
export interface Task {
  'id' : bigint,
  'title' : string,
  'isCompleted' : boolean,
  'description' : string,
  'points' : bigint,
}
export interface TaskInput {
  'title' : string,
  'description' : string,
  'points' : bigint,
}
export interface TaskUpdate {
  'title' : string,
  'description' : string,
  'points' : bigint,
}
export type Time = bigint;
export interface UserProfile {
  'name' : string,
  'role' : UserRole,
  'avatarId' : string,
}
export type UserRole = { 'student' : null } |
  { 'parent' : null };
export type UserRole__1 = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole__1], undefined>,
  'awardBadge' : ActorMethod<[Principal, string], undefined>,
  'completeLesson' : ActorMethod<[bigint], undefined>,
  'createTask' : ActorMethod<[TaskInput], Task>,
  'getAllSessionsProgress' : ActorMethod<[], Array<[string, SessionProgress]>>,
  'getCallerRole' : ActorMethod<[], UserRole>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole__1>,
  'getDisplayName' : ActorMethod<[Principal], [] | [string]>,
  'getFlashcards' : ActorMethod<[], Array<Flashcard>>,
  'getGameTypeAverage' : ActorMethod<
    [GameType],
    [] | [{ 'totalSessions' : bigint, 'averageScore' : bigint }]
  >,
  'getLessons' : ActorMethod<[], Array<Lesson>>,
  'getMiniGameContent' : ActorMethod<[], Array<MiniGameContent>>,
  'getQuizQuestions' : ActorMethod<[], Array<QuizQuestion>>,
  'getSessionProgress' : ActorMethod<[Principal], SessionProgress>,
  'getTasks' : ActorMethod<[], Array<Task>>,
  'getUserGameSessions' : ActorMethod<[Principal], Array<GameSession>>,
  'getUserGameStatistics' : ActorMethod<
    [Principal, GameType],
    [] | [GameStatistics]
  >,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getUserRole' : ActorMethod<[Principal], UserRole>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'markTaskComplete' : ActorMethod<[bigint], [] | [Task]>,
  'recordGameSession' : ActorMethod<
    [GameType, string, bigint, bigint],
    undefined
  >,
  'recordQuizResult' : ActorMethod<[string, bigint, bigint], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setCallerRole' : ActorMethod<[UserRole], undefined>,
  'setDisplayName' : ActorMethod<[string], undefined>,
  'setupContent' : ActorMethod<[], undefined>,
  'updateTask' : ActorMethod<[bigint, TaskUpdate], [] | [Task]>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];