/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole__1 = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const QuizResult = IDL.Record({
  'total' : IDL.Nat,
  'subject' : IDL.Text,
  'score' : IDL.Nat,
});
export const SessionProgress = IDL.Record({
  'earnedBadges' : IDL.Vec(IDL.Text),
  'completedLessons' : IDL.Vec(IDL.Nat),
  'quizResults' : IDL.Vec(QuizResult),
});
export const UserRole = IDL.Variant({
  'student' : IDL.Null,
  'parent' : IDL.Null,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text, 'role' : UserRole });
export const Flashcard = IDL.Record({
  'id' : IDL.Nat,
  'front' : IDL.Text,
  'back' : IDL.Text,
  'image' : IDL.Text,
});
export const GameType = IDL.Variant({
  'quiz' : IDL.Null,
  'matchingGame' : IDL.Null,
  'puzzle' : IDL.Null,
  'timedChallenge' : IDL.Null,
});
export const Lesson = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'body' : IDL.Text,
  'image' : IDL.Text,
});
export const MiniGameContent = IDL.Record({
  'id' : IDL.Nat,
  'pairs' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text)),
});
export const QuizQuestion = IDL.Record({
  'id' : IDL.Nat,
  'question' : IDL.Text,
  'correctIndex' : IDL.Nat,
  'options' : IDL.Vec(IDL.Text),
});
export const Time = IDL.Int;
export const GameSession = IDL.Record({
  'userId' : IDL.Principal,
  'score' : IDL.Nat,
  'language' : IDL.Text,
  'totalQuestions' : IDL.Nat,
  'timestamp' : Time,
  'gameType' : GameType,
});
export const GameStatistics = IDL.Record({
  'bestScore' : IDL.Nat,
  'totalScore' : IDL.Nat,
  'totalSessions' : IDL.Nat,
  'averageScore' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole__1], [], []),
  'awardBadge' : IDL.Func([IDL.Principal, IDL.Text], [], []),
  'completeLesson' : IDL.Func([IDL.Nat], [], []),
  'getAllSessionsProgress' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Text, SessionProgress))],
      ['query'],
    ),
  'getCallerRole' : IDL.Func([], [UserRole], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole__1], ['query']),
  'getDisplayName' : IDL.Func([IDL.Principal], [IDL.Opt(IDL.Text)], ['query']),
  'getFlashcards' : IDL.Func([], [IDL.Vec(Flashcard)], ['query']),
  'getGameTypeAverage' : IDL.Func(
      [GameType],
      [
        IDL.Opt(
          IDL.Record({ 'totalSessions' : IDL.Nat, 'averageScore' : IDL.Nat })
        ),
      ],
      ['query'],
    ),
  'getLessons' : IDL.Func([], [IDL.Vec(Lesson)], ['query']),
  'getMiniGameContent' : IDL.Func([], [IDL.Vec(MiniGameContent)], ['query']),
  'getQuizQuestions' : IDL.Func([], [IDL.Vec(QuizQuestion)], ['query']),
  'getSessionProgress' : IDL.Func(
      [IDL.Principal],
      [SessionProgress],
      ['query'],
    ),
  'getUserGameSessions' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(GameSession)],
      ['query'],
    ),
  'getUserGameStatistics' : IDL.Func(
      [IDL.Principal, GameType],
      [IDL.Opt(GameStatistics)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getUserRole' : IDL.Func([IDL.Principal], [UserRole], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'recordGameSession' : IDL.Func(
      [GameType, IDL.Text, IDL.Nat, IDL.Nat],
      [],
      [],
    ),
  'recordQuizResult' : IDL.Func([IDL.Text, IDL.Nat, IDL.Nat], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setCallerRole' : IDL.Func([UserRole], [], []),
  'setDisplayName' : IDL.Func([IDL.Text], [], []),
  'setupContent' : IDL.Func([], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole__1 = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const QuizResult = IDL.Record({
    'total' : IDL.Nat,
    'subject' : IDL.Text,
    'score' : IDL.Nat,
  });
  const SessionProgress = IDL.Record({
    'earnedBadges' : IDL.Vec(IDL.Text),
    'completedLessons' : IDL.Vec(IDL.Nat),
    'quizResults' : IDL.Vec(QuizResult),
  });
  const UserRole = IDL.Variant({ 'student' : IDL.Null, 'parent' : IDL.Null });
  const UserProfile = IDL.Record({ 'name' : IDL.Text, 'role' : UserRole });
  const Flashcard = IDL.Record({
    'id' : IDL.Nat,
    'front' : IDL.Text,
    'back' : IDL.Text,
    'image' : IDL.Text,
  });
  const GameType = IDL.Variant({
    'quiz' : IDL.Null,
    'matchingGame' : IDL.Null,
    'puzzle' : IDL.Null,
    'timedChallenge' : IDL.Null,
  });
  const Lesson = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'body' : IDL.Text,
    'image' : IDL.Text,
  });
  const MiniGameContent = IDL.Record({
    'id' : IDL.Nat,
    'pairs' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text)),
  });
  const QuizQuestion = IDL.Record({
    'id' : IDL.Nat,
    'question' : IDL.Text,
    'correctIndex' : IDL.Nat,
    'options' : IDL.Vec(IDL.Text),
  });
  const Time = IDL.Int;
  const GameSession = IDL.Record({
    'userId' : IDL.Principal,
    'score' : IDL.Nat,
    'language' : IDL.Text,
    'totalQuestions' : IDL.Nat,
    'timestamp' : Time,
    'gameType' : GameType,
  });
  const GameStatistics = IDL.Record({
    'bestScore' : IDL.Nat,
    'totalScore' : IDL.Nat,
    'totalSessions' : IDL.Nat,
    'averageScore' : IDL.Nat,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole__1], [], []),
    'awardBadge' : IDL.Func([IDL.Principal, IDL.Text], [], []),
    'completeLesson' : IDL.Func([IDL.Nat], [], []),
    'getAllSessionsProgress' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Text, SessionProgress))],
        ['query'],
      ),
    'getCallerRole' : IDL.Func([], [UserRole], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole__1], ['query']),
    'getDisplayName' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(IDL.Text)],
        ['query'],
      ),
    'getFlashcards' : IDL.Func([], [IDL.Vec(Flashcard)], ['query']),
    'getGameTypeAverage' : IDL.Func(
        [GameType],
        [
          IDL.Opt(
            IDL.Record({ 'totalSessions' : IDL.Nat, 'averageScore' : IDL.Nat })
          ),
        ],
        ['query'],
      ),
    'getLessons' : IDL.Func([], [IDL.Vec(Lesson)], ['query']),
    'getMiniGameContent' : IDL.Func([], [IDL.Vec(MiniGameContent)], ['query']),
    'getQuizQuestions' : IDL.Func([], [IDL.Vec(QuizQuestion)], ['query']),
    'getSessionProgress' : IDL.Func(
        [IDL.Principal],
        [SessionProgress],
        ['query'],
      ),
    'getUserGameSessions' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(GameSession)],
        ['query'],
      ),
    'getUserGameStatistics' : IDL.Func(
        [IDL.Principal, GameType],
        [IDL.Opt(GameStatistics)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getUserRole' : IDL.Func([IDL.Principal], [UserRole], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'recordGameSession' : IDL.Func(
        [GameType, IDL.Text, IDL.Nat, IDL.Nat],
        [],
        [],
      ),
    'recordQuizResult' : IDL.Func([IDL.Text, IDL.Nat, IDL.Nat], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setCallerRole' : IDL.Func([UserRole], [], []),
    'setDisplayName' : IDL.Func([IDL.Text], [], []),
    'setupContent' : IDL.Func([], [], []),
  });
};

export const init = ({ IDL }) => { return []; };