/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const KidsProfile = IDL.Record({
  'age' : IDL.Nat,
  'pin' : IDL.Text,
  'name' : IDL.Text,
  'avatar' : IDL.Text,
});
export const QuizResult = IDL.Record({
  'total' : IDL.Nat,
  'subject' : IDL.Text,
  'score' : IDL.Nat,
});
export const SessionProgress = IDL.Record({
  'earnedBadges' : IDL.Vec(IDL.Text),
  'completedLessons' : IDL.Vec(IDL.Nat),
  'quizResults' : IDL.Vec(QuizResult),
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'avatarUrl' : IDL.Text,
});
export const Flashcard = IDL.Record({
  'id' : IDL.Nat,
  'front' : IDL.Text,
  'back' : IDL.Text,
  'image' : IDL.Text,
});
export const GameType = IDL.Variant({
  'quiz' : IDL.Null,
  'matchingGame' : IDL.Null,
  'puzzle' : IDL.Null,
  'timedChallenge' : IDL.Null,
});
export const AnimalCard = IDL.Record({
  'nameHindi' : IDL.Text,
  'nameTelugu' : IDL.Text,
  'nameEnglish' : IDL.Text,
  'audioUrl' : IDL.Text,
  'imageUrl' : IDL.Text,
});
export const StateInfo = IDL.Record({
  'nameHindi' : IDL.Text,
  'stateId' : IDL.Nat,
  'capitalEnglish' : IDL.Text,
  'nameTelugu' : IDL.Text,
  'nameEnglish' : IDL.Text,
  'emoji' : IDL.Text,
  'capitalHindi' : IDL.Text,
  'capitalTelugu' : IDL.Text,
});
export const AdditionProblem = IDL.Record({
  'hindi' : IDL.Text,
  'answer' : IDL.Nat,
  'firstNumber' : IDL.Nat,
  'telugu' : IDL.Text,
  'secondNumber' : IDL.Nat,
  'english' : IDL.Text,
});
export const BodyPart = IDL.Record({
  'nameHindi' : IDL.Text,
  'nameTelugu' : IDL.Text,
  'nameEnglish' : IDL.Text,
  'audioUrl' : IDL.Text,
  'imageUrl' : IDL.Text,
});
export const NumberCard = IDL.Record({
  'hindi' : IDL.Text,
  'audioUrl' : IDL.Text,
  'number' : IDL.Nat,
  'telugu' : IDL.Text,
  'english' : IDL.Text,
});
export const PlantCard = IDL.Record({
  'nameHindi' : IDL.Text,
  'nameTelugu' : IDL.Text,
  'nameEnglish' : IDL.Text,
  'audioUrl' : IDL.Text,
  'imageUrl' : IDL.Text,
});
export const LearningContentPackage = IDL.Record({
  'animalCards' : IDL.Vec(AnimalCard),
  'stateInfos' : IDL.Vec(StateInfo),
  'additionProblems' : IDL.Vec(AdditionProblem),
  'bodyParts' : IDL.Vec(BodyPart),
  'numberCards' : IDL.Vec(NumberCard),
  'plantCards' : IDL.Vec(PlantCard),
});
export const Lesson = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'body' : IDL.Text,
  'image' : IDL.Text,
});
export const MiniGameContent = IDL.Record({
  'id' : IDL.Nat,
  'pairs' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text)),
});
export const ParentalControls = IDL.Record({
  'gamesAllowed' : IDL.Vec(IDL.Nat),
  'contentRestrictions' : IDL.Vec(IDL.Text),
});
export const QuizQuestion = IDL.Record({
  'id' : IDL.Nat,
  'question' : IDL.Text,
  'correctIndex' : IDL.Nat,
  'options' : IDL.Vec(IDL.Text),
});
export const Time = IDL.Int;
export const GameSession = IDL.Record({
  'userId' : IDL.Principal,
  'score' : IDL.Nat,
  'language' : IDL.Text,
  'totalQuestions' : IDL.Nat,
  'timestamp' : Time,
  'gameType' : GameType,
});
export const GameStatistics = IDL.Record({
  'bestScore' : IDL.Nat,
  'totalScore' : IDL.Nat,
  'totalSessions' : IDL.Nat,
  'averageScore' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'awardBadge' : IDL.Func([IDL.Principal, IDL.Text], [], []),
  'completeLesson' : IDL.Func([IDL.Nat], [], []),
  'createKidsProfile' : IDL.Func([KidsProfile], [], []),
  'getAllSessionsProgress' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Text, SessionProgress))],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getDisplayName' : IDL.Func([], [IDL.Opt(IDL.Text)], ['query']),
  'getFlashcards' : IDL.Func([], [IDL.Vec(Flashcard)], ['query']),
  'getGameTypeAverage' : IDL.Func(
      [GameType],
      [
        IDL.Opt(
          IDL.Record({ 'totalSessions' : IDL.Nat, 'averageScore' : IDL.Nat })
        ),
      ],
      ['query'],
    ),
  'getKidsProfile' : IDL.Func([], [IDL.Opt(KidsProfile)], ['query']),
  'getLearningContentPackage' : IDL.Func(
      [],
      [LearningContentPackage],
      ['query'],
    ),
  'getLessons' : IDL.Func([], [IDL.Vec(Lesson)], ['query']),
  'getMiniGameContent' : IDL.Func([], [IDL.Vec(MiniGameContent)], ['query']),
  'getParentalControls' : IDL.Func([], [IDL.Opt(ParentalControls)], ['query']),
  'getQuizQuestions' : IDL.Func([], [IDL.Vec(QuizQuestion)], ['query']),
  'getSessionProgress' : IDL.Func(
      [IDL.Principal],
      [SessionProgress],
      ['query'],
    ),
  'getUserGameSessions' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(GameSession)],
      ['query'],
    ),
  'getUserGameStatistics' : IDL.Func(
      [IDL.Principal, GameType],
      [IDL.Opt(GameStatistics)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'recordGameSession' : IDL.Func(
      [GameType, IDL.Text, IDL.Nat, IDL.Nat],
      [],
      [],
    ),
  'recordQuizResult' : IDL.Func([IDL.Text, IDL.Nat, IDL.Nat], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setDisplayName' : IDL.Func([IDL.Text], [], []),
  'setParentalControls' : IDL.Func([ParentalControls], [], []),
  'setupContent' : IDL.Func([], [], []),
  'setupLearningContent' : IDL.Func([], [], []),
  'updateKidsPin' : IDL.Func([IDL.Text], [], []),
  'updateKidsProfile' : IDL.Func([KidsProfile], [], []),
  'verifyKidsPin' : IDL.Func([IDL.Text], [IDL.Bool], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const KidsProfile = IDL.Record({
    'age' : IDL.Nat,
    'pin' : IDL.Text,
    'name' : IDL.Text,
    'avatar' : IDL.Text,
  });
  const QuizResult = IDL.Record({
    'total' : IDL.Nat,
    'subject' : IDL.Text,
    'score' : IDL.Nat,
  });
  const SessionProgress = IDL.Record({
    'earnedBadges' : IDL.Vec(IDL.Text),
    'completedLessons' : IDL.Vec(IDL.Nat),
    'quizResults' : IDL.Vec(QuizResult),
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'avatarUrl' : IDL.Text,
  });
  const Flashcard = IDL.Record({
    'id' : IDL.Nat,
    'front' : IDL.Text,
    'back' : IDL.Text,
    'image' : IDL.Text,
  });
  const GameType = IDL.Variant({
    'quiz' : IDL.Null,
    'matchingGame' : IDL.Null,
    'puzzle' : IDL.Null,
    'timedChallenge' : IDL.Null,
  });
  const AnimalCard = IDL.Record({
    'nameHindi' : IDL.Text,
    'nameTelugu' : IDL.Text,
    'nameEnglish' : IDL.Text,
    'audioUrl' : IDL.Text,
    'imageUrl' : IDL.Text,
  });
  const StateInfo = IDL.Record({
    'nameHindi' : IDL.Text,
    'stateId' : IDL.Nat,
    'capitalEnglish' : IDL.Text,
    'nameTelugu' : IDL.Text,
    'nameEnglish' : IDL.Text,
    'emoji' : IDL.Text,
    'capitalHindi' : IDL.Text,
    'capitalTelugu' : IDL.Text,
  });
  const AdditionProblem = IDL.Record({
    'hindi' : IDL.Text,
    'answer' : IDL.Nat,
    'firstNumber' : IDL.Nat,
    'telugu' : IDL.Text,
    'secondNumber' : IDL.Nat,
    'english' : IDL.Text,
  });
  const BodyPart = IDL.Record({
    'nameHindi' : IDL.Text,
    'nameTelugu' : IDL.Text,
    'nameEnglish' : IDL.Text,
    'audioUrl' : IDL.Text,
    'imageUrl' : IDL.Text,
  });
  const NumberCard = IDL.Record({
    'hindi' : IDL.Text,
    'audioUrl' : IDL.Text,
    'number' : IDL.Nat,
    'telugu' : IDL.Text,
    'english' : IDL.Text,
  });
  const PlantCard = IDL.Record({
    'nameHindi' : IDL.Text,
    'nameTelugu' : IDL.Text,
    'nameEnglish' : IDL.Text,
    'audioUrl' : IDL.Text,
    'imageUrl' : IDL.Text,
  });
  const LearningContentPackage = IDL.Record({
    'animalCards' : IDL.Vec(AnimalCard),
    'stateInfos' : IDL.Vec(StateInfo),
    'additionProblems' : IDL.Vec(AdditionProblem),
    'bodyParts' : IDL.Vec(BodyPart),
    'numberCards' : IDL.Vec(NumberCard),
    'plantCards' : IDL.Vec(PlantCard),
  });
  const Lesson = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'body' : IDL.Text,
    'image' : IDL.Text,
  });
  const MiniGameContent = IDL.Record({
    'id' : IDL.Nat,
    'pairs' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text)),
  });
  const ParentalControls = IDL.Record({
    'gamesAllowed' : IDL.Vec(IDL.Nat),
    'contentRestrictions' : IDL.Vec(IDL.Text),
  });
  const QuizQuestion = IDL.Record({
    'id' : IDL.Nat,
    'question' : IDL.Text,
    'correctIndex' : IDL.Nat,
    'options' : IDL.Vec(IDL.Text),
  });
  const Time = IDL.Int;
  const GameSession = IDL.Record({
    'userId' : IDL.Principal,
    'score' : IDL.Nat,
    'language' : IDL.Text,
    'totalQuestions' : IDL.Nat,
    'timestamp' : Time,
    'gameType' : GameType,
  });
  const GameStatistics = IDL.Record({
    'bestScore' : IDL.Nat,
    'totalScore' : IDL.Nat,
    'totalSessions' : IDL.Nat,
    'averageScore' : IDL.Nat,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'awardBadge' : IDL.Func([IDL.Principal, IDL.Text], [], []),
    'completeLesson' : IDL.Func([IDL.Nat], [], []),
    'createKidsProfile' : IDL.Func([KidsProfile], [], []),
    'getAllSessionsProgress' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Text, SessionProgress))],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getDisplayName' : IDL.Func([], [IDL.Opt(IDL.Text)], ['query']),
    'getFlashcards' : IDL.Func([], [IDL.Vec(Flashcard)], ['query']),
    'getGameTypeAverage' : IDL.Func(
        [GameType],
        [
          IDL.Opt(
            IDL.Record({ 'totalSessions' : IDL.Nat, 'averageScore' : IDL.Nat })
          ),
        ],
        ['query'],
      ),
    'getKidsProfile' : IDL.Func([], [IDL.Opt(KidsProfile)], ['query']),
    'getLearningContentPackage' : IDL.Func(
        [],
        [LearningContentPackage],
        ['query'],
      ),
    'getLessons' : IDL.Func([], [IDL.Vec(Lesson)], ['query']),
    'getMiniGameContent' : IDL.Func([], [IDL.Vec(MiniGameContent)], ['query']),
    'getParentalControls' : IDL.Func(
        [],
        [IDL.Opt(ParentalControls)],
        ['query'],
      ),
    'getQuizQuestions' : IDL.Func([], [IDL.Vec(QuizQuestion)], ['query']),
    'getSessionProgress' : IDL.Func(
        [IDL.Principal],
        [SessionProgress],
        ['query'],
      ),
    'getUserGameSessions' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(GameSession)],
        ['query'],
      ),
    'getUserGameStatistics' : IDL.Func(
        [IDL.Principal, GameType],
        [IDL.Opt(GameStatistics)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'recordGameSession' : IDL.Func(
        [GameType, IDL.Text, IDL.Nat, IDL.Nat],
        [],
        [],
      ),
    'recordQuizResult' : IDL.Func([IDL.Text, IDL.Nat, IDL.Nat], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setDisplayName' : IDL.Func([IDL.Text], [], []),
    'setParentalControls' : IDL.Func([ParentalControls], [], []),
    'setupContent' : IDL.Func([], [], []),
    'setupLearningContent' : IDL.Func([], [], []),
    'updateKidsPin' : IDL.Func([IDL.Text], [], []),
    'updateKidsProfile' : IDL.Func([KidsProfile], [], []),
    'verifyKidsPin' : IDL.Func([IDL.Text], [IDL.Bool], []),
  });
};

export const init = ({ IDL }) => { return []; };